apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  finalizers:
    - >-
      cert-manager-operator.operator.openshift.io/cert-manager-webhook-deployment
    - >-
      cert-manager-operator.operator.openshift.io/cert-manager-cainjector-deployment
    - >-
      cert-manager-operator.operator.openshift.io/cert-manager-controller-deployment
  name: cluster
spec:
  controllerConfig:
    overrideArgs:
      - '--dns01-recursive-nameservers=8.8.8.8:53'
      - '--dns01-recursive-nameservers-only'
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
